### ISSUE TITLE
Fix typo in setup.sh

### ISSUE THREAD

**Issue by Michael-Jiahao-Zhang** [Ringbo/CCT5#1]
It should be "pip install scipy==1.10.1;" instead of "pip install cipy==1.10.1;"

**Comment by Ringbo** [comment]
> It should be "pip install scipy==1.10.1;" instead of "pip install cipy==1.10.1;"

We apologise for our mistake and thank you for your feedback.

**Comment by Michael-Jiahao-Zhang** [comment]
The `setup.sh` should be updated to:

```
#!/bin/bash

function setup_repo() {
    cd myParser;
    bash build.sh;
    cd ../
}

function create_and_activate() {
    conda create --name cct5 python=3.8;
    conda activate cct5;
}

function install_deps() {
    conda install torch=2.0.0+cu117 torchvision=0.15.1 torchaudio cudatoolkit=11.7 -c pytorch -c conda-forge
    conda install datasets==1.16.1 -c conda-forge
    conda install transformers==4.21.1 -c conda-forge
    conda install tensorboard==2.12.2 -c conda-forge
    pip install tree-sitter==0.19.1;
    pip install nltk==3.8.1;
    pip install scipy==1.10.1;
}

create_and_activate;
install_deps;
setup_repo;
```

**Comment by Michael-Jiahao-Zhang** [comment]
Additionally, when executing `pip install tree-sitter==0.19.1;`
```
ERROR: Could not find a version that satisfies the requirement tree-sitter==0.19.1 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.1.0, 0.1.1, 0.2.0, 0.2.1, 0.2.2, 0.19.0, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.20.4)
ERROR: No matching distribution found for tree-sitter==0.19.1
```

I personally use `pip install tree-sitter==0.20.0` which should work.

**Comment by Ringbo** [comment]
> Additionally, when executing `pip install tree-sitter==0.19.1;`
> 
> ```
> ERROR: Could not find a version that satisfies the requirement tree-sitter==0.19.1 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.1.0, 0.1.1, 0.2.0, 0.2.1, 0.2.2, 0.19.0, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.20.4)
> ERROR: No matching distribution found for tree-sitter==0.19.1
> ```
> 
> I personally use `pip install tree-sitter==0.20.0` which should work.

The issue may be due to your use of the PyPi mirror, which doesn't contain the TreeSitter version 0.19.1. However, I believe version 0.20.0 should be compatible.

**Comment by Ringbo** [comment]
> We apologise for our mistake and thank you for your feedback.

Thank you for your feedback. I've update the setup.sh.
