### ISSUE TITLE
Inquiry About How to Convert Code Change into Vectors

### ISSUE THREAD

**Issue by Michael-Jiahao-Zhang** [Ringbo/CCT5#2]
I want to utilize CCT5 to convert code change into vectors, but I am lost in the huge amount of code. Would you be kind enough to give me some guidance regarding that?

**Comment by Ringbo** [comment]
Thank you for your interest.
You can consider the first output of the encoder as the embedding of code changes. Please refer to this [link](https://github.com/Ringbo/CCT5/blob/69a8453a9fa187c3f39eb409aa9bc20d947f8942/src/models.py#L811).

**Comment by Michael-Jiahao-Zhang** [comment]
Thank you so much for your kind reply! I really appreciate your work on the CCT5 model.

Could you please provide more detailed instructions on how to use the code you mentioned? I've attempted to execute the scripts from the start and added lots of logging statements to understand how the `review_forward` and `forward` functions can be used to obtain the embedding of code changes. However, I've been stuck here for another several days. I am still wondering this code snippet is utilized during the pre-training or fine-tuning phase. What steps should I follow(where to stop) to simply learn how to transform code changes into vectors/embeddings? What are the other code snippets that I need to refer to when I am trying to transform code changes into vectors/embeddings?

Our team has been working here for a really extended period and is now facing an urgent deadline. We would greatly appreciate any guidance or assistance you can provide!

Less important details:
I am running it on a Linux server from my university, but without `sudo` permission, there are a lot of scripts I need to modify. Thus, I am also trying to run CCT5 on my local MacOS (M2 silicon), but even I have collected CCT5.tar.bz2 and all the CCT5.tar.bz2.a[a~j] after running `bash setup.sh, I have failed the MD5 check twice:
```
2023-11-28 22:08:20 (2.32 MB/s) - ‘CCT5.tar.bz2.aj’ saved [59255180/59255180]

MD5 check failed. Please delete the downloaded file and re-run the script.
```

**Comment by Michael-Jiahao-Zhang** [comment]
I complete the `Just-in-Time Comment Update` task while skipping the [optional] steps. However, my logging/print code snippets around `hidden_states = encoder_outputs[0]` doesn't work. Does that mean that the code is used in the **pretraining phase** instead of **fine-tuning**?

I got the result for Task 2 as below
```
Total: 9204
{'gleu': 0.707732, 'bleu': 73.32, 'acc': 36.09300304215559}
```
