### ISSUE TITLE
Question about input order.

### ISSUE THREAD

**Issue by ZZX-11** [Ringbo/CCT5#3]
Dear Authors:
Thank you for your excellent work！I have a question when I deal with my data. Would the outcome be affected if I input all the 'add-lines' before the 'delete-lines' without formatting the diff-lines according to the commit format in your paper?
For example:
A：[add] line1 [add] line2 [add] line3, [del] line1 [del] line2 [del] line3,
B：[add] line1 [del] line1 [add] line2 [del] line2 [add] line3 [del] line3
If I input the data in format A, would the outcome differ from format B?
I'm still relatively new to AI, so I truly appreciate your insights.

**Comment by Ringbo** [comment]
Thank you for your interest. IMHO, I see no obvious difference between the two input formats, as long as the format is consistent from the pre-training phase to the fine-tuning phase. However, actions speak louder than words. We look forward to seeing the investigation results and hope you can share them with us if you research the influence of performance based on different input formats.

**Comment by xuwenyou11** [comment]
So inspiring work this is. I love it veri much!
